version: '3.8'
services:
  graph-db:
    image: neo4j:enterprise
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=eval
      - NEO4J_dbms_memory_transaction_total_max=0
    volumes:
      - my_neo4j_data:/data
    networks:
      - mynetwork
  bloom-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8000:8000
networks:
  mynetwork:
volumes:
  my_neo4j_data:
